version: "3"
services:
  web:
    build: ./frontend/
    container_name: vue_frontend
    ports:
      - 8080:8080
    environment:
      - BACKEND_URL=http://localhost:3000
    links:
      - rails
    depends_on:
      - rails
  rails:
    build: ./backend/
    command: bash -c "cd backend && rm -f tmp/pids/server.pid && bundle exec rake db:drop && bundle exec rake db:create && bundle exec rake db:migrate  && bundle exec rails s -p 3000 -b '0.0.0.0'"
    container_name: rails_backend
    ports:
      - 3000:3000
    volumes:
      - .:/app
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    links:
      - db
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5431:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
